// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bobs_burger_api.Data;

#nullable disable

namespace bobs_burger_api.Migrations
{
    [DbContext(typeof(BobsBurgerContext))]
    partial class BobsBurgerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bobs_burger_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<int>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ingredient",
                            Description = "Deliciously melted cheese",
                            Ingredients = new List<int>(),
                            Name = "cheese",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "ingredient",
                            Description = "No better buns exist",
                            Ingredients = new List<int>(),
                            Name = "bun",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "ingredient",
                            Description = "Very green",
                            Ingredients = new List<int>(),
                            Name = "lettuce",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "ingredient",
                            Description = "Bobs super special, super secret burger sauce",
                            Ingredients = new List<int>(),
                            Name = "bobs-secret-sauce",
                            Price = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "ingredient",
                            Description = "100% juicy meat",
                            Ingredients = new List<int>(),
                            Name = "beef-patty",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Category = "ingredient",
                            Description = "Fermented for days",
                            Ingredients = new List<int>(),
                            Name = "pickle",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "ingredient",
                            Description = "Could make you cry",
                            Ingredients = new List<int>(),
                            Name = "onion",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Category = "ingredient",
                            Description = "Very red",
                            Ingredients = new List<int>(),
                            Name = "ketchup",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 9,
                            Category = "ingredient",
                            Description = "Very yellow",
                            Ingredients = new List<int>(),
                            Name = "mustard",
                            Price = 1.0
                        },
                        new
                        {
                            Id = 10,
                            Category = "burger",
                            Description = "Biggest bob there is",
                            Ingredients = new List<int> { 1, 2, 3, 4, 5, 6, 7 },
                            Name = "Big Bob",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 11,
                            Category = "burger",
                            Description = "Biggest bob there is",
                            Ingredients = new List<int> { 1, 2, 4, 6, 7, 8, 9 },
                            Name = "Quarter Bob",
                            Price = 9.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
